# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    # Group PRs to reduce spam
    groups:
      gatsby:
        patterns:
          - gatsby
          - 'gatsby-*'
      react:
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      sentry:
        patterns:
          - '@sentry/*'

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
